[tool.poetry]
name = "dbt_coves"
version = "0.1.0"
description = "CLI tool for dbt users that follow the datacoves guidelines."
authors = ["Sebastian Sassi <ssassi@gmail.com>, Noel Gomez <gomezn@gmail.com>, Michael Kahan <mjkahan23@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
luddite = "^1.0.1"
packaging = "^20.8"
pretty-errors = "^1.2.19"
snowflake-sqlalchemy = ">=1.2.4"
SQLAlchemy = ">=1.3.0,<1.4.0"
pydantic = "^1.8"
PyYAML = "^5.4.1"
questionary = "^1.9.0"
yamlloader = "^1.0.0"
pyfiglet = "^0.8.post1"
rich = ">=9.13,<11.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dbt-coves="dbt_coves.core.main:main"
