name: Github Tag and Release

on:
  push:
    branches:
      - main
    paths:
      - dbt_coves/__init__.py
    #   - pyproject.toml
    #   - .bumpversion.cfg

jobs:
  tag_and_release:
    name: Github tag and release
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Bump version')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install toml-cli
        run: cargo install toml-cli

      - name: Extract version
        run: |
          dbtcoves_version=$(toml get pyproject.toml tool.poetry.version)
          echo "::set-output name=dbtcoves_version::$dbtcoves_version"

      - name: Github tag and release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: "v${{ steps.extract_version.outputs.dbtcoves_version }}"
          release_name: "v${{ steps.extract_version.outputs.dbtcoves_version }}"
